### ISSUE TITLE
evaluate() function

### ISSUE THREAD

**Issue by RushiBhatt007** [wzh9969/contrastive-htc#8]
Thank you for producing a great paper and making the codebase public; it is very inspiring.

I had a question regarding the `evaluate()` function from `eval.py` file. The paper focuses on working with datasets with hierarchy, but while evaluating, seems like those hierarchy are not taken care of? Meaning at the end there is a flat-classification and probability scores (dimension = no. of total unique classes) is generated; now afterwards we see that the `evaluate()` function prepares `right_count_list` after thresholding these probabilities without taking into consideration the hierarchy? Also, why are the final scores taken purely based on list counts, and not comparing `pred` and `truth` element-wise?

I am also worries about scenarios where `threshold` is chosen to be very small (~0) and then `right_count_list` would exactly match `predicted_count_list`.

I believe one approach of handling this would be performing evaluation level-wise; meaning first pick class with highest probability in level-0, then among children of that class, pick class with highest probability in level-1 and so on.

Please share your thoughts, and feedback.

**Comment by wzh9969** [comment]
The evaluation part is adopted from previous work (from [HiAGM repo](https://github.com/Alibaba-NLP/HiAGM/blob/master/train_modules/evaluation_metrics.py)) and we actually fix a bug where previous code cannot handle classes with same label names.

The problem is a multi-path problem (if viewed on the hierarchy tree, one or more paths from root to any node) so we are not sure how many classes should be picked on each level. WOS is a single-path dataset (which is special and can be predicted as you mentioned) but NYT and RCV1-V2 are not. Viewing the problem as a flat classification is one simple way to avoid such difficulties and of course, there are other solutions and they deserve other works to study on. Due to multi-path again, `pred` and `truth` may have a different number of classes so that they cannot be compared element-wise.

`right_count_list` contains classes in both `pred` and `truth` while `predict_count_list` contains all predictions in `pred`. If `threshold` is close to 0, all classes are predicted, `right_count_list` = `gold_count_list` but `predicted_count_list` will contains all classes. This leads to high recall and low precision and low F1 as ordinary multi-class classification. BTW, `threshold=0.5` is a standard setting when using `Sigmoid + BCE` (once again, multi-label classification where we don't know the number of predicted labels) so `threshold` should not be very small.
